export const data = {
  navLinks: [
    { href: '#objective', label: 'Objective' },
    { href: '#education', label: 'Education' },
    { href: '#skills', label: 'Skills' },
    { href: '#projects', label: 'Projects' },
    { href: '#experience', label: 'Experience' },
    { href: '#training', label: 'Training' },
    { href: '#certifications', label: 'Certs' },
    { href: '#achievements', label: 'Achievements' },
  ],
  profile: {
    name: 'Vinamra Jain',
    initials: 'VJ',
    title: 'Power BI Developer | Oracle AI Foundation Certified | Sports Analytics | Salesforce Intern @ Smartbridge | Trailhead Four Star Ranger | Gemini Certified University Student | B.Tech, GGITS',
    location: 'Jabalpur, Madhya Pradesh',
    email: 'vinamra.jain.csbs22@gmail.com',
    phone: '+91 9142888365',
    imageId: 'profile',
    resumeUrl: 'https://drive.google.com/file/d/1p6UK8oYUD9bG6zmLlV2xY8Ki5kHTeBPZ/view?usp=sharing',
    socials: [
      { name: 'LinkedIn', url: 'https://linkedin.com/in/vinab17' },
      { name: 'Linktree', url: 'https://linktr.ee/vin_ab17' },
    ],
  },
  careerObjective:
    'Analytics-focused professional with hands-on experience in data analytics, business intelligence, Salesforce development, and financial modeling. Skilled in transforming complex datasets into actionable insights using Power BI, Excel, Python, and Salesforce tools.',
  education: [
    {
      degree: 'B.Tech – Computer Science and Business Systems',
      institution: 'Gyan Ganga Institute of Technology and Sciences, Jabalpur',
      period: 'Oct 2022 – Jun 2026',
      gpa: 'CGPA: 8.21',
    },
    {
      degree: 'Higher Secondary (CBSE)',
      institution: 'Agrasen DAV Public School, Jabalpur',
      period: '2022',
      gpa: 'Percentage: 81.6%',
    },
    {
      degree: 'Secondary School (CBSE)',
      institution: 'Agrasen DAV Public School, Jabalpur',
      period: '2020',
      gpa: 'Percentage: 87.6%',
    },
  ],
  skills: [
    {
      category: 'Data Analytics & BI',
      technologies: ['Power BI', 'Excel', 'DAX', 'Data Modeling', 'KPI Design', 'Data Visualization'],
    },
    {
      category: 'Programming & Machine Learning',
      technologies: ['Python', 'SQL', 'Statistics', 'Scikit-Learn', 'XGBoost', 'TensorFlow'],
    },
    {
      category: 'Platforms & Tools',
      technologies: ['Salesforce', 'Power Apps', 'SharePoint', 'Microsoft Fabric', 'Google Colab', 'WEKA', 'RapidMiner'],
    },
    {
      category: 'Additional Areas',
      technologies: ['Financial Modeling', 'Valuation Analysis', 'Networking', 'UML Design'],
    },
  ],
  projects: [
    {
      title: 'IPL 2025 Dashboard',
      imageId: 'project-ipl-dashboard',
      description: 'Interactive Power BI dashboard analyzing IPL 2025 team and player performance using KPIs, drill-through analysis, and match-wise trends.',
      role: 'Data Analyst / Sports Analytics',
      stack: ['Power BI', 'Excel', 'DAX'],
      timeline: '2025',
      links: [{ name: 'Project Link', url: 'https://app.powerbi.com/view?r=eyJrIjoiNTdkYjlkODctZjJkMy00OTY1LWJmYjQtOTI0MjMwMjVjZjNkIiwidCI6IjRhNzhmOWQwLWFiZGUtNDBjNC1hMDg4LTBiOTg5NTk5M2M0YSJ9' }],
    },
    {
      title: 'Result Analysis Dashboard',
      imageId: 'project-result-analysis',
      description: 'Academic analytics dashboard evaluating student performance across semesters and departments.',
      role: 'Data Analyst',
      stack: ['Power BI', 'Excel'],
      timeline: '2024',
      links: [{ name: 'Project Link', url: 'https://app.powerbi.com/view?r=eyJrIjoiOGFhYjE1ZTEtOWRmOS00ZDY3LTk0YzYtNzgyYWUyNDU5YjRiIiwidCI6IjRhNzhmOWQwLWFiZGUtNDBjNC1hMDg4LTBiOTg5NTk5M2M0YSJ9' }],
    },
    {
      title: 'COVID-19 Global Analysis Dashboard',
      imageId: 'project-covid-analysis',
      description: 'Global COVID-19 monitoring dashboard using geo-maps and slicers for country-wise trend analysis.',
      role: 'Data Analyst',
      stack: ['Power BI', 'Excel'],
      timeline: '2024',
      links: [{ name: 'Project Link', url: 'https://app.powerbi.com/view?r=eyJrIjoiZTY4ZmFjMDItMzI5Zi00M2IwLWFjMDUtNThmZjY5ODk3Y2RlIiwidCI6IjRhNzhmOWQwLWFiZGUtNDBjNC1hMDg4LTBiOTg5NTk5M2M0YSJ9' }],
    },
    {
      title: 'CertiMagic',
      imageId: 'project-certimagic',
      description: 'Built an AI-powered platform for bulk generation of personalized certificates with template uploads, dynamic name placement, AI-based style suggestions, secure authentication, saved history, and batch downloads.',
      role: 'Full Stack Developer',
      stack: ['Next.js', 'TypeScript', 'Firebase (Authentication, Firestore)', 'Tailwind CSS', 'Genkit', 'ShadCN UI'],
      timeline: '2025',
      links: [{ name: 'Project Link', url: 'https://certi-magic.vercel.app/' }],
    },
    {
      title: 'Food Expiry Alert System',
      imageId: 'project-food-expiry',
      description: 'Design Thinking prototype to reduce food waste by tracking expiry dates and generating alerts.',
      role: 'Product Analyst',
      stack: ['Design Thinking', 'Canva'],
      timeline: '2023',
      links: [{ name: 'Project Link', url: 'https://tinyurl.com/ysy6dswp' }],
    },
    {
      title: 'CSBS Academic Management System – Salesforce',
      imageId: 'project-csbs-salesforce',
      description: 'Salesforce-based faculty and student portals to automate attendance, subject management, and academic workflows.',
      role: 'Salesforce Developer',
      stack: ['Salesforce Platform', 'Workflows', 'Reports', 'Dashboards'],
      timeline: '2025',
      links: [
        { name: 'Faculty', url: 'https://brave-bear-noe056-dev-ed.trailblaze.my.site.com/facultypage/' },
        { name: 'Student', url: 'https://brave-bear-noe056-dev-ed.trailblaze.my.site.com/studentpage/' }
      ],
    },
    {
      title: 'Smart Disease Prediction (ML + Power BI)',
      imageId: 'project-disease-prediction',
      description: 'Predictive healthcare analytics solution integrating machine learning models with Power BI dashboards.',
      role: 'Machine Learning Engineer / Data Analyst',
      stack: ['Python', 'Scikit-Learn', 'XGBoost', 'TensorFlow', 'Power BI', 'DAX', 'Microsoft Fabric'],
      timeline: '2025',
      links: [{ name: 'Project Link', url: 'https://app.powerbi.com/view?r=eyJrIjoiNTEyMmU3YjktMWI0YS00OTEzLWIwMDctYmE0MjU1NjdjMjMwIiwidCI6IjRhNzhmOWQwLWFiZGUtNDBjNC1hMDg4LTBiOTg5NTk5M2M0YSJ9' }],
    },
    {
      title: 'Netflix Valuation Case Study',
      imageId: 'project-netflix-valuation',
      description: 'End-to-end financial modeling and valuation of Netflix including revenue forecasting, financial statements, PP&E schedules, and DCF valuation using WACC.',
      role: 'Financial Analyst',
      stack: ['Financial Modeling', 'Excel', 'DCF', 'WACC'],
      timeline: '2025',
      links: [{ name: 'Project Link', url: 'https://1drv.ms/x/c/279dc6546c66c500/EcvKAOF6unBGkqsE__vwAEoBRkA6ZJ0iUGDLvVT8dlucCw' }],
    },
  ],
  experience: [
    {
      role: 'Data Analyst',
      organization: 'Gyan Ganga Genesis Incubation Centre, Jabalpur',
      duration: 'Feb 2026 – Present',
      responsibilities: [
        'Working on institutional data analysis, dashboard development, and performance reporting to support data-driven academic and administrative decision-making.',
      ],
    },
    {
      role: 'Salesforce Intern',
      organization: 'SmartBridge Educational Services Pvt. Ltd., Hyderabad',
      duration: 'Sept 2025 to Feb 2026',
      responsibilities: [
        'Salesforce customization, reporting, deployment, documentation, and platform support.',
      ],
      url: 'https://www.linkedin.com/feed/update/urn:li:activity:7373612467555500032/',
    },
  ],
  training: [
    {
      title: 'LastMile Program – Salesforce AI Agent Developer Track',
      issuer: 'SmartBridge Educational Services Pvt. Ltd.',
      date: 'Jul 2025 – Oct 2025',
      description: 'Salesforce AI Agent development, platform customization, and applied AI use cases.',
      certificateId: 'LM-SF-2025-0059',
      url: 'https://media.licdn.com/dms/image/v2/D4D2DAQEjg8ivouqevA/profile-treasury-document-cover-images_1920/B4DZtaLjC7GUBM-/0/1766744540734?e=1778317200&v=beta&t=ZxCvp_mzgd9PJJrkvhJId4b1sW4eMbEkrjN_oLLpzoI'
    },
    {
      title: 'Power BI for Future Tech Leaders: Data Analytics & Visualization',
      issuer: 'Computer Science and Business Systems Department, GGITS',
      date: 'Mar 2025',
      description: 'Hands-on training in Power BI Desktop, data modeling, DAX calculations, dashboard creation, data shaping, and performance optimization.',
      certificateId: 'CERT-1767161318863-BORS5TY',
      url: 'https://media.licdn.com/dms/image/v2/D4D22AQEf3sUZIiENog/feedshare-shrink_800/B4DZuofxYRI4Ag-/0/1768058461837?e=1779321600&v=beta&t=jJEh17_1HA5okCreejkVnmtTkljXGQWfrLhAN6oPPBQ'
    }
  ],
  certifications: [
    {
      title: 'Oracle Cloud Infrastructure 2025 Certified AI Foundation Associate',
      issuer: 'Oracle',
      date: '',
      url: 'https://www.linkedin.com/in/vinab17/details/certifications/1759430971663/single-media-viewer',
      isGlobal: true,
    },
    {
      title: 'SAP Certified - Data Analyst - SAP Analytics Cloud',
      issuer: 'SAP',
      date: '',
      url: 'https://www.credly.com/badges/feb4661a-6762-4920-bd7f-62dcd3f7cf5a/public_url',
      isGlobal: true,
    },
    {
      title: 'SAP Certified Project_Manager-SAP Activate.',
      issuer: 'SAP',
      date: '',
      url: 'https://www.credly.com/badges/75e28e10-4cf2-40e1-ba8f-664abd9cca0d/public_url',
      isGlobal: true,
    },
    {
      title: 'IBM AI Fundamentals',
      issuer: 'IBM',
      date: '',
      url: 'https://www.linkedin.com/in/vinab17/details/certifications/1759312766961/single-media-viewer',
    },
    {
      title: 'Analyzing and Visualizing Data with Microsoft Power BI',
      issuer: 'Microsoft',
      date: '',
      url: 'https://www.linkedin.com/in/vinab17/details/certifications/1752320403136/single-media-viewer',
    },
    {
      title: 'Financial Modelling & Valuation',
      issuer: '',
      date: '',
      url: 'https://www.linkedin.com/in/vinab17/details/certifications/1759312830642/single-media-viewer',
    },
    {
      title: 'HP Design Thinking',
      issuer: 'HP',
      date: '',
      url: 'https://www.linkedin.com/in/vinab17/details/certifications/1769065222380/single-media-viewer',
    },
    {
      title: 'TCS Communication Skills (TCS iON)',
      issuer: 'TCS',
      date: '',
      url: 'https://www.linkedin.com/in/vinab17/details/certifications/1741788114678/single-media-viewer',
    },
    {
      title: 'Data Visualization: Empowering Business with Effective Insights (TATA Group)',
      issuer: 'TATA Group',
      date: '',
      url: 'https://www.linkedin.com/in/vinab17/details/certifications/1739966633860/single-media-viewer',
    },
    {
      title: 'Google Analytics 4',
      issuer: 'Google',
      date: '',
      url: 'https://skillshop.credential.net/e57c9192-2c20-4a75-b1b7-102b13686f94#acc.KnhB9M8c',
    },
  ],
  achievements: [
    {
      title: 'SIH 2023 Finalist',
      description: '',
      url: 'https://media.licdn.com/dms/image/v2/D4D2DAQHXb33W9Tt2oQ/profile-treasury-document-cover-images_480/B4DZUeJQM9GkAw-/0/1739967499383?e=1778320800&v=beta&t=YhdkIsT8oxvfxBlQCeaYhjbKzQyoK6eimwXMDXEx8KM',
    },
    {
      title: 'IDE Bootcamp Participant (MoE)',
      description: '',
      url: 'https://media.licdn.com/dms/image/v2/D4D2DAQFAXCTl3J-2Gw/profile-treasury-document-cover-images_480/B4DZUeJrJHHIA0-/0/1739967611050?e=1778320800&v=beta&t=gu28oienh6mQ8xJIJrpgL98ZUnr6gpryQsBIpkm757g',
    },
    {
      title: 'College Bronze Medalist – Best Academics (2023–24)',
      description: '',
      url: 'https://media.licdn.com/dms/image/v2/D4D2DAQETIYPLFAOeqA/profile-treasury-document-cover-images_480/B4DZUeKGzfHAA0-/0/1739967723376?e=1778320800&v=beta&t=1B0o0IfsNFszbI5POIYjBbYH5BJ0rjdB0nnRZa_IV90',
    },
    {
      title: 'Four Star Ranger – Salesforce Trailhead',
      description: '',
      url: 'https://www.salesforce.com/trailblazer/k58sla6vezvtay691k',
    },
    {
      title: 'Google Cloud Gen AI Academy APAC Edition Participation',
      description: '',
      url: 'https://certificate.hack2skill.com/verify/2026H2S04GCGENAIAPACC1-P01396',
    },
    {
      title: 'AI Impact Summit 2026 India Participation',
      description: '',
      url: 'https://cdn.indiaai.in/6YWAVK__1770932814459_1770932814459.png?Expires=1776116814',
    },
    {
      title: 'Agentforce World Tour Tokyo Participation',
      description: '',
      url: 'https://www.linkedin.com/posts/vinab17_worldabrtourabrtokyoabrsummerabr2026-salesforce-activity-7451524858762383360-_r8g?utm_source=share&utm_medium=member_desktop&rcm=ACoAAFVZsgsB-U3O6iE9Zwg6M0f7Gifpz6WTvg0',
    },
    {
      title: 'GenAI Academy 2.0 by Google Cloud Participation',
      description: '',
      url: 'https://media.licdn.com/dms/image/v2/D4D2DAQFlQY6zRR8ehw/profile-treasury-document-cover-images_1920/B4DZtaKNTRKoBU-/0/1766744186492?e=1778320800&v=beta&t=pslnr86ICwn7X9by_vYUdwqDqR4MLJ6EHwHNvRGNGK8',
    },
    {
      title: 'Google Certified University Student',
      description: '',
      url: 'https://edu.google.accredible.com/dbd8705c-9947-40ad-b3c9-e91b335f5505',
    },
    {
      title: 'Google Certified Educator Level 1',
      description: '',
      url: 'https://edu.google.accredible.com/d0390675-9034-47fb-9fc0-cc363d31857c',
    },
    {
      title: 'Google Certified Educator Level 2',
      description: '',
      url: 'https://edu.google.accredible.com/323497a1-7c1c-41ca-9849-b73885cfe1be#acc.M0UmzZae',
    },
  ],
  softSkills: ['Critical Thinking', 'Problem Solving', 'Time Management', 'Decision Making', 'Adaptability'],
  additionalSkills: ['Social Media Management', 'Visual Design (Canva)', 'Creative Writing', 'Strategic Planning'],
  languages: ['English (B2)', 'Hindi (C1)', 'German (A2)'],
  interests: ['Sports Analytics', 'Cricket', 'Formula 1', 'Content Creation', 'Anime', 'Gaming', 'Music'],
};
